services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5332:5432
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin
    restart: unless-stopped